### ISSUE TITLE
Can't Remove Nodeserver

### ISSUE THREAD

**Issue by lenp2001** [sjpbailey/udi-poly-baspi6u6r-garage-doors-python-master#3]
I installed this by mistake and don't need this nodeserver however it wont let me fully uninstall
It has it listed as a possible AddNodeserver but I don't want it there. I am having other issues and troubleshooting so I have no servers at all
I can remove it form my ISY, I can delete it form my Dashboard, but then if I go to addservers its there to install and I want it gone
I go to The store and it only shows the option to install not uninstall. Very odd I haven't seen this before with other nodeservers
I did try a factory reset of the Polisy but it keep writing some config back n for some reason.
If you can help Id appreciate it. Thanks

**Comment by sjpbailey** [comment]
Hello Lenp2001,

Interesting no uninstall button? Sorry about that!

 I will have to get a hold of one of the administrators for the store as it will probably need to be re-added to the Store it had lots of edits.

Are you running a Polisy or an RPI? 

You have the option of uninstalling it manually if you know DOS or Unix commands. They are cool BACnet controllers if you ever need a nice WiFi controller with 6 inputs and 6 outputs.

Regards,
Steve

**Comment by lenp2001** [comment]
Michael from Universal-Devices sent me the Unix commands needed. All is well! Thanks you can now close the request!


 Len
 Owner \ President

 PTACloud LLC
 Office: 815.334.0201
 Cell:     312.833.8215

 Network Administration / VOIP / Cloud Hosting / System Design
P       Please consider the environment before printing. Thank you!

**Comment by sjpbailey** [comment]
Cool!

THANK YOU for the heads up on the Store!

It needs to be re-added to the store because the install and update are from there and not the Node Server itself.

Regards
